### PR TITLE
PLAT-78609: Remove deprecated props

### PR DESCRIPTION
**Pull request by viodragon2**
### Checklist

* [x] I have read and understand the [contribution guide](http://enactjs.com/docs/developer-guide/contributing/)
* [x] A [CHANGELOG entry](http://enactjs.com/docs/developer-guide/contributing/changelogs/) is included
* [ ] At least one test case is included for this feature or bug fix
* [x] Documentation was added or is not needed

* [x] This is an API breaking change

### Issue Resolved / Feature Added
[//]: # (Describe the issue resolved or feature added by this pull request)
Remove deprecated props
- `small` prop in `moonstone/Input`, `moonstone/ToggleButton`, `moonstone/Button`, `moonstone/Icon`, `moonstone/IconButton`, and `moonstone/LabeledIcon`
-  `core/kind` config property `contextTypes`

Enact-DCO-1.0-Signed-off-by: Stephen Choi <stephen.choi@lge.com>

### CODE REVIEW

**Comment by Djspaceg** [comment]
It may be helpful for us and app developers to discover places where `small` wasn't removed (since it won't get a React warning) for us to add an interesting global CSS rule, something like:
```
[small] {
   outline: 3px red solid;
   &::before {
      position: absolute;
      outline: 3px red solid;
      content: "A stray `small` prop exists on this element";
   }
}
```
This will highlight any element which still has a `small` prop that blead onto the DOM node ("illegal").

**Comment by webOS101** [comment]
That's a neat idea... but it'd have to be in develop mode only.  I can't suggest we break the appearance of deployed apps.  I think we could use that in the future during the deprecation phase, maybe?

**Comment by Djspaceg** [comment]
Could be done behind the `.debug` global class.

**Comment by webOS101** [comment]
I'm merging this as-is.  I'd like to discuss that css thing in another ticket or separately so we can get this removal in for today's release.

**Pull request merged**
