### PR TITLE
ENYO-6188: Add overflow hidden property to FormCheckboxItem

### PR DESCRIPTION
**Pull request by xbinary**
Enact-DCO-1.0-Signed-off-by: Hyeok Jo <hyeok.jo@lge.com>

### Checklist

* [x] I have read and understand the [contribution guide](http://enactjs.com/docs/developer-guide/contributing/)
* [ ] A [CHANGELOG entry](http://enactjs.com/docs/developer-guide/contributing/changelogs/) is included
* [ ] At least one test case is included for this feature or bug fix
* [ ] Documentation was added or is not needed

* [ ] This is an API breaking change

### Issue Resolved / Feature Added
Ellipses don't occur in FormCheckboxItem.
It is reproduced from rc.2.

### Resolution
Add `overflow: hidden` to `span` tag which contain `children`.

### Links
ENYO-6188

### CODE REVIEW

**Comment by Djspaceg** [comment]
I'm concerned that this isn't the "right" approach. For example, if the problem is truly unique to FormCheckboxItem, then maybe this makes sense. However, that being said, FormCheckboxItem is based on the same thing that many other toggleable components are, and it's not unique in its visual representation of the toggle state (a checkmark), so it may be a bigger issue with Marquee or ToggleItem, and this would just be a superficial patch fix that we should address at a deeper level instead and fix all of the issues, rather than just the reported one.

**Comment by Djspaceg** [comment]
To follow up with the comment above, an alternate approach that does not apply new rules would be to publish (add to publicClassNames) the `content` class name defined in ToggleItem, and remove the `span` tag from FormCheckboxItem entirely. This way, the content can still be styled for FormCheckboxItem (setting disabled opacity on content), we remove a DOM node, we don't duplicate CSS and intruduce potential bugs by creating unique scenarios for marquee, and leverage the existing class names and structure. Thoughts?

**Comment by teckliew** [comment]
Opening up `content` class name would also simplify this as well:
https://github.com/enactjs/enact/pull/2483/files#diff-78698fc6d858b953a97382e93928f5ecR62

**Comment by Djspaceg** [comment]
I think it's ok to accept this for this release and address this again, more holistically in the upcoming release.

What I was thinking was to refactor Marquee to expose its `.marquee` class through its hocs in our standard way (it's already public via the MarqueeBase), via the `css` prop, rather than exposing a design-time config key "className" which doesn't leverage our fancy CSS overrides mechanism. This will involve adding `css` prop support into the HOC layers of Marquee, but will be much more intuitive to use in the future. FormCheckboxItem and Button, as well as others, could immediately use the new approach and become simpler in the process.

**Pull request merged**
