### PR TITLE
ENYO-6130: Pass spotlightDisabled prop from list or scroller to scroll buttons

### PR DESCRIPTION
**Pull request by ybsung**
### Checklist

* [X] I have read and understand the [contribution guide](http://enactjs.com/docs/developer-guide/contributing/)
* [X] A [CHANGELOG entry](http://enactjs.com/docs/developer-guide/contributing/changelogs/) is included
* [ ] At least one test case is included for this feature or bug fix
* [X] Documentation was added or is not needed
* [ ] This is an API breaking change

### Issue Resolved / Feature Added
[//]: # (Describe the issue resolved or feature added by this pull request)

Even though a list or a scroller has a `spotlightDisabled` prop, the scroll buttons in it has spotlight when holding them.

### Resolution
[//]: # (Does the code work as intended?)
[//]: # (What is the impact of this change and *why* was it made?)

Pass spotlightDisabled prop from a list or a scroller to scroll buttons

### Links
[//]: # (Related issues, references)

ENYO-6130

### CODE REVIEW

**Comment by 0x64** [comment]
Maybe there would be a better name for the new prop, but I don't have any better idea. :)
So, looks good to me.

**Comment by ryanjduffy** [comment]
@ybsung - Can you elaborate on the root cause and why this is the appropriate solution? Why are the scroll buttons focusable but items are not?

**Comment by ybsung** [comment]
Hello @ryanjduffy 

> Can you elaborate on the root cause and why this is the appropriate solution? Why are the scroll buttons focusable but items are not?

I had to find the root cause. But it was very hard to me. According to my analysis, if `spotlightDisabled` prop was applied to Scroller, then Spottable.handleFocus() in the item was not called when clicking it. But Spottable.handleFocus() is the Scroll Button was called when clicking. So it would be the start point to debug more.

If I add Scrollbars as the content in Scroller, Spottable.handleFocus() in the Scroll Button of the scrollbars is not called. So there might no problem with item or scrollbars.

So I just passed `spotlightDisabled` prop to the Scroll button to blur in Spottable.handleFocus() to solve the problem simply.

**Comment by ybsung** [comment]
Hello @germboy 
Do you have any hint for my comment above to know why Spottable.handleFocus() in the Scroll Button was called when clicking?

**Comment by ryanjduffy** [comment]
I think the reason items are not focusable is due to the `onMouseDown` handler in `moonstone/Scrollable`:

https://github.com/enactjs/enact/blob/develop/packages/moonstone/Scrollable/Scrollable.js#L378-L382

For some reason, that handler is attached to the internal container and not the root node so it isn't able to suppress focus on the scroll buttons.

**Comment by 0x64** [comment]
Closing in favor of #2468

**Pull request closed without merging**
