### PR TITLE
PLAT-99658: Fixed to cover scrollbars also with scrim when container is muted

### PR DESCRIPTION
**Pull request by 0x64**
### Checklist

* [x] I have read and understand the [contribution guide](http://enactjs.com/docs/developer-guide/contributing/)
* [ ] A [CHANGELOG entry](http://enactjs.com/docs/developer-guide/contributing/changelogs/) is included
* [ ] At least one test case is included for this feature or bug fix
* [x] Documentation was added or is not needed
* [ ] This is an API breaking change

### Issue Resolved / Feature Added
[//]: # (Describe the issue resolved or feature added by this pull request)
A scrim for a muted container of a scroller or a list does not cover scrollbars properly.

### Resolution
[//]: # (Does the code work as intended?)
[//]: # (What is the impact of this change and *why* was it made?)
Moved related CSS to the top node of scrollable components.

### Additional Considerations
[//]: # (How should the change be tested?)
[//]: # (Are there any outstanding questions?)
[//]: # (Were any side-effects caused by the change?)
This change is also required to support a muted container in other theme libs.

### Links
[//]: # (Related issues, references)
PLAT-99658

### CODE REVIEW

**Comment by 0x64** [comment]
Note: we have a `ref` issue for `touchable` scroller now. It needs to be fixed. @MikyungKim any idea?

**Comment by MikyungKim** [comment]
@0x64, I think we could pass `ref` directly to the `ScrollContentWrapper` instead of using `ForwardRef`. WDYT?

**Comment by 0x64** [comment]
> @0x64, I think we could pass `ref` directly to the `ScrollContentWrapper` instead of using `ForwardRef`. WDYT?

👍

**Comment by 0x64** [comment]
The `ref` issue resolved with prop bypassing on `Touchable`.

**Pull request merged**
