### PR TITLE
PLAT-86939: Update Moonstone Icon (updated sizes)

### PR DESCRIPTION
**Pull request by teckliew**
### Checklist

* [x] I have read and understand the [contribution guide](http://enactjs.com/docs/developer-guide/contributing/)
* [x] A [CHANGELOG entry](http://enactjs.com/docs/developer-guide/contributing/changelogs/) is included
* [ ] At least one test case is included for this feature or bug fix
* [x] Documentation was added or is not needed

* [ ] This is an API breaking change

### Issue Resolved / Feature Added
[//]: # (Describe the issue resolved or feature added by this pull request)
Update with Moonstone Icon with sizes fixed to fit within the margins

### CODE REVIEW

**Comment by ryanjduffy** [comment]
Before

image

After

image

**Comment by ryanjduffy** [comment]
Forgot ... @teckliew let's tack on a change log as well. Otherwise :shipit:

**Comment by Djspaceg** [comment]
We're going to ask about the remaining overflowing icon glyph, which we think is intentional, but want to verify it A) is intentional B) whether it should be aligned with its twin icon: `(A)-(B)` and `(A)-(B)x`

**Comment by teckliew** [comment]
LIke Blake said, just gave feed back about `repeat` and `repeatoff` icons in the ticket, and if that's good to go, we can push this pr ahead.

**Pull request merged**
