### PR TITLE
ENYO-6430: Fix console error when wheel on ui native Scroller

### PR DESCRIPTION
**Pull request by seunghoh**
### Checklist

* [X] I have read and understand the [contribution guide](http://enactjs.com/docs/developer-guide/contributing/)
* [ ] A [CHANGELOG entry](http://enactjs.com/docs/developer-guide/contributing/changelogs/) is included
* [ ] At least one test case is included for this feature or bug fix
* [ ] Documentation was added or is not needed

* [ ] This is an API breaking change

### Issue Resolved / Feature Added
[//]: # (Describe the issue resolved or feature added by this pull request)
Fixed Uncaught TypeErrorr when wheeling on ui native Scroller

### Resolution
[//]: # (Does the code work as intended?)
[//]: # (What is the impact of this change and *why* was it made?)
Change to call getter `getContainerRef()` which referred to the wrong ref in the `onWheel`

### Links
[//]: # (Related issues, references)
ENYO-6430

### CODE REVIEW

**Comment by jeonghee27** [comment]
image

Another console error still occurs.

**Comment by seunghoh** [comment]
I Checked only on Scroller which has horizontal ref, vertical ref both regardless of orientation. Added check on VirtualList case which has only oneway directional ref

**Comment by jeonghee27** [comment]
LGTM

**Comment by MikyungKim** [comment]
When Scroller with native mode and direction vertical, I got 
```
Uncaught TypeError: Cannot read property 'getContainerRef' of null
    at HTMLDivElement.onWheel (useScroll.js:658)
```
I think we need to check `horizontalScrollbarRef.current` and `verticalScrollbarRef.current` 's exsitence.

**Comment by MikyungKim** [comment]
LGTM!

**Pull request merged**
