### PR TITLE
ENYO-5543: Use perfNow() over Date.now()

### PR DESCRIPTION
**Pull request by viodragon2**
### Checklist

* [x] I have read and understand the [contribution guide](http://enactjs.com/docs/developer-guide/contributing/)
* [x] A [CHANGELOG entry](http://enactjs.com/docs/developer-guide/contributing/changelogs/) is included
* [ ] At least one test case is included for this feature or bug fix
* [ ] Documentation was added or is not needed

* [ ] This is an API breaking change

### Issue Resolved / Feature Added
[//]: # (Describe the issue resolved or feature added by this pull request)
Use `perfNow()` over `Date.now()` in `Spotlight/Accelerator`

Enact-DCO-1.0-Signed-off-by: Stephen Choi <stephen.choi@lge.com>

### CODE REVIEW

**Comment by ryanjduffy** [comment]
Why? :)

**Comment by viodragon2** [comment]
for better performance

**Comment by ryanjduffy** [comment]
But https://jsperf.com/perf-vs-date/1?

image

**Comment by viodragon2** [comment]
👎

**Pull request closed without merging**
