### PR TITLE
PLAT-62418: Fixed to scroll properly when holding down paging control buttons

### PR DESCRIPTION
**Pull request by 0x64**
### Issue Resolved / Feature Added
[//]: # (Describe the issue resolved or feature added by this pull request)
Fixed a bug that a list or a scroller does not scroll until a user releases the button if a user holds down a paging control button right after pressing the opposite paging control button.

### Resolution
[//]: # (Does the code work as intended?)
[//]: # (What is the impact of this change and *why* was it made?)
After #1570, a focus does not move to the opposite paired button but it stays on the current button even if the button is disabled by scrolling. This bug occurs by old code to prevent scrolling from `holdpulse` events when a focus moved to the opposite button during holding down.
So, removed the old code.

### Links
[//]: # (Related issues, references)
PLAT-62418

### Comments
Enact-DCO-1.0-Signed-off-by: Seungcheon Baek (sc.baek@lge.com)

### CODE REVIEW

**Comment by ybsung** [comment]
LGTM, but please update CHANGELOG.md.

**Comment by 0x64** [comment]
@ybsung I will update CHANGELOG.md later. As you know, it can make a conflict frequently if we update it too early, so intentionally I defer updating normally.

**Comment by MikyungKim** [comment]
Please add CHANGELOG.

**Comment by 0x64** [comment]
Updated CHANGELOG.md!

**Comment by MikyungKim** [comment]
LGTM

**Pull request merged**
