### PR TITLE
ENYO-5502: Fix Image to hide broken image icon when image loading fails

### PR DESCRIPTION
**Pull request by viodragon2**
### Checklist

* [x] I have read and understand the [contribution guide](http://enactjs.com/docs/developer-guide/contributing/)
* [x] A [CHANGELOG entry](http://enactjs.com/docs/developer-guide/contributing/changelogs/) is included
* [ ] At least one test case is included for this feature or bug fix
* [x] Documentation was added or is not needed

* [ ] This is an API breaking change

### Issue Resolved / Feature Added
[//]: # (Describe the issue resolved or feature added by this pull request)
Broken image icon appears even if height and width are set to 0 in webOS.

### Resolution
[//]: # (Does the code work as intended?)
[//]: # (What is the impact of this change and *why* was it made?)
Set `ui/Image`'s `` visibility hidden

### Additional Considerations
[//]: # (How should the change be tested?)
[//]: # (Are there any outstanding questions?)
[//]: # (Were any side-effects caused by the change?)
Setting `display: none` does the same trick but it changes the vertical alignment.

See https://codepen.io/stephenhchoi/pen/wxXjOq?editors=1100 for the sample. The red box mimics the `Button` and blue mimics `Image`.

Enact-DCO-1.0-Signed-off-by: Stephen Choi <stephen.choi@lge.com>

### CODE REVIEW

**Comment by ryanjduffy** [comment]
I'm curious why we're "hiding" the `` using zero width/height vs a more explicit means (display/visibility/opacity). As far as I can tell, there's no case in which we need it to be visible and Chrome (latest, at least) doesn't appear to report `error` or `load` differently for an `` with `display: none`.

https://codepen.io/anon/pen/rrKvyK?editors=0010

**Comment by viodragon2** [comment]
The broken image icon only appears in webOS TV even with width/height 0. It doesn't reproduce the same issue in Chrome.

**Comment by ryanjduffy** [comment]
I understand but my question is still if we can fully hide the `` all the time and thereby avoid that behavior.

**Comment by viodragon2** [comment]
Thanks for the input.  Updated to set `visibility: hidden` at all times for ``. I'm not sure why `display: none` changes the layout when aligned with other `inline-block` elements. So I decided to go with `visibility: hidden` for now. If anybody can explain what causes the misalignment, I'd appreciate it.

**Comment by Djspaceg** [comment]
Buckle up, here's why the alignment changes. _(Remember, you asked for this.)_

Inline-blocks work like text. By default, they align on their baseline. When a div has no content, its baseline is the same as the "bottom". By setting `display: none` you're telling the `div` that it no longer has any contents, and it should align according to its own dimensions (ignoring children). When you set the size of the `img` inside the top set of divs, the blue box still has content, and that content (the 0x0 `img` also has a baseline – 1em). It's actually not in the upper left corner but about 1em down from the top left because it is vertically aligned with the baseline of the "text" it is pretending to be (since images are inline-block). This position inside the blue box is then middle aligned with the red box, because the red box was told to be middle aligned. The vertical-middle of the red box is where following siblings will anchor to, and in this case, it's the baseline of the child of the blue box, which is 1em down from the top left corner of the blue box. Meanwhile, back to the bottom pair, the blue box has no children (because of `display: none`) so it is anchoring its bottom (baseline) to the vertical middle of the red box.

The attached image shows a little orange square. This is the 0x0 image. Note it aligns perfectly with the middle of the red box, and 1em down from the top of the blue box.
Box alignment issue

**Comment by Djspaceg** [comment]
My opinion is that `display: none`, if it doesn't cause any loading or event-firing issues, is the way to go. The blue box will behave more intuitively with no (text/inline) content inside.

**Pull request merged**
