### PR TITLE
ENYO-5184: Restore focus after mounting VirtualList

### PR DESCRIPTION
**Pull request by ybsung**
### Issue Resolved / Feature Added
[//]: # (Describe the issue resolved or feature added by this pull request)

When `componentDidUpdate` in `VirtualListBase` is called, we tried to restore focus in `VirtualList`. But if the number of items are small, `componentDidUpdate` was not called. So focus was not restored.

### Resolution
[//]: # (Does the code work as intended?)
[//]: # (What is the impact of this change and *why* was it made?)

When `componentDidMount` in `VirtualListBase` is called, I tried to restore focus after generating all DOM elements.

### Additional Considerations
[//]: # (How should the change be tested?)
[//]: # (Are there any outstanding questions?)
[//]: # (Were any side-effects caused by the change?)

The solution in this PR depends on timing. If VirtualList renders asynchronously. the approach in this PR would have a problem. But currently, there is no alternative solution. So I hope that we could merge the PR first. Then we could find the best solution for it later.

### Links
[//]: # (Related issues, references)

ENYO-5184

### Comments

Enact-DCO-1.0-Signed-off-by: YB Sung (yb.sung@lge.com)

### CODE REVIEW

**Comment by 0x64** [comment]
It looks not so good to call `timeout` in `componentDidMount` regarding complex life cycle of lists, but I agree that it is our best for now. We cannot gaurantee `componentUpdate` cycle to be called at the first rendering or not for various scenarios.

**Comment by 0x64** [comment]
LGTM

**Comment by MikyungKim** [comment]
I think we should revisit this issue later.

**Comment by MikyungKim** [comment]
LGTM..

**Pull request merged**
