### PR TITLE
PLAT-77661: QA Sampler-Button with tap area displayed: added taparea to IconButton and a divider to viewport

### PR DESCRIPTION
**Pull request by LucieRoy**
### Checklist

* [x] I have read and understand the [contribution guide](http://enactjs.com/docs/developer-guide/contributing/)
* [ ] A [CHANGELOG entry](http://enactjs.com/docs/developer-guide/contributing/changelogs/) is included
* [x] At least one test case is included for this feature or bug fix
* [x] Documentation was added or is not needed

* [ ] This is an API breaking change

### Issue Resolved / Feature Added
[//]: # (Describe the issue resolved or feature added by this pull request)

### Resolution
[//]: # (Does the code work as intended?)
[//]: # (What is the impact of this change and *why* was it made?)

### Additional Considerations
[//]: # (How should the change be tested?)
[//]: # (Are there any outstanding questions?)
[//]: # (Were any side-effects caused by the change?)

### Links
[//]: # (Related issues, references)

### CODE REVIEW

**Comment by Djspaceg** [comment]
I think this may need to be merged into `feature/ui-update` rather than `develop`. I'll wait for confirmation before switching it.

**Comment by LucieRoy** [comment]
Correct! good catch! was my first fix on this branch! Thank you!

**Comment by Djspaceg** [comment]
Retargeted. Much smaller change-set now. Also, this means that this doesn't need to go into the 2.x release. If you *do* want it in the 2.x release branch, it will need to be rebased on `develop` and re-targeted back to `develop` as well.

**Comment by Djspaceg** [comment]
Why were tap areas added to large buttons? Large Buttons don't have or need tap areas.

**Comment by webOS101** [comment]
For consistency, it makes sense to me.

**Comment by Djspaceg** [comment]
But it's a sample/story explicitly for showing tap areas. If a component doesn't have a tap area, it shouldn't _show_ a non-existent tap area. That's misleading as to what's going on and what is being tested. The point is to verify and validate that large buttons don't have a mistakenly or unintentionally applied tap area and to show that small buttons _have_ a tap area and what size it is.

**Comment by webOS101** [comment]
That was my point.  If some CSS applied a tap area around large buttons but we didn't show it, that's be an issue, wouldn't it?  Or, am I misunderstanding?

**Comment by Djspaceg** [comment]
If something had unintentionally applied a tap area, it would appear and be visually apparent in this test. If we artificially insert a tap area in the sample, we can't tell if a tap area was added to the framework component.

Large buttons don't have tap areas because they don't need them. They're already above the minimum tap-target dimensions. A small button is only 60px tall, which is 20px smaller than the minimum tap-target dimensions, so we add an invisible tap area to make it easier to tap with the Magic Remote. This sample makes the invisible tap area visible.

**Comment by webOS101** [comment]
I understand what you are saying.  What about the case of the large `IconButton` which has a square tap target?  It was not rendered appropriately with this test without modification.  I actually suspect the change in the border radius could possibly mislead, given that the small button used to have an expanded, but round, tap area.

**Comment by LucieRoy** [comment]
The contrast of the tap area color blue is not as obvious on black as a brighter color. Red? Bright green? Orange?Why was blue chosen?

**Pull request merged**
