### PR TITLE
ENYO-4978: Add Tooltip to ProgressBar

### PR DESCRIPTION
**Pull request by teckliew**
### Issue Resolved / Feature Added
[//]: # (Describe the issue resolved or feature added by this pull request)
Add `tooltip` to `ProgressBar`.

`tooltip` follows the progress bar and shows the percentage of the progress bar.

`forceTooltipSide` is also added to support for cases where Tooltip needs to be switched to the other side when `vertical` progress bar is at the right edge of the container.

### Additional Considerations
[//]: # (How should the change be tested?)
[//]: # (Are there any outstanding questions?)
[//]: # (Were any side-effects caused by the change?)
`SliderTooltip` is pulled out to be in `Tooltip` as `ProgressBarTooltip`

### Links
[//]: # (Related issues, references)
ENYO-4978

### Comments
Enact-DCO-1.0-Signed-off-by: Teck Liew teck.liew@lge.com

### CODE REVIEW

**Comment by viodragon2** [comment]
Everything looks good. Can you resolve :mergeconflict:?

**Comment by ryanjduffy** [comment]
@teckliew Can you elaborate on why you placed `ProgressBarTooltip` into `Tooltip`?

**Comment by ryanjduffy** [comment]
@teckliew + @viodragon2 - WDYT of moving `ProgressBarTooltip` "back" to `moonstone/ProgressBar` and also exporting it as `SliderTooltip` from `moonstoneSlider`? I think that would make the API more predictable (both behave the same) and easier to use (only have to import the module for the component you're using).

**Comment by ryanjduffy** [comment]
Here's a branch with the change for consideration: https://github.com/enactjs/enact/tree/feature/ENYO-4978-ryan

**Comment by viodragon2** [comment]
In general, I agree with your approach. The only downside I see with that approach is that `moonstone/Slider` is still importing a module that doesn't belong to the component. It would make much more sense if slider utilizes the progress bar as a core component, which I believe it's postponed for now.

**Comment by ryanjduffy** [comment]
I agree. The advantage is it avoids the deprecation and likely positions us for the future in which we do reuse ProgressBar within Slider.

**Comment by teckliew** [comment]
I am still unsure if having `ProgressBarTooltip` in `Tooltip` is the best idea, but because this is a component that is based on `Tooltip` that is used by both `Slider` and `ProgressBar`, I felt this makes sense. Like what @viodragon2 said, it also makes sense set up `ProgressBar` as the core component of `Slider`. I am indifferent so let me know what you guys decided on.

**Comment by Djspaceg** [comment]
Can we also merge Ryan's changes if they're satisfactory?

**Pull request merged**
