### PR TITLE
PLAT-69511: Add line-height in the base font mixin

### PR DESCRIPTION
**Pull request by Djspaceg**
### Checklist

* [x] I have read and understand the [contribution guide](http://enactjs.com/docs/developer-guide/contributing/)
* [ ] A [CHANGELOG entry](http://enactjs.com/docs/developer-guide/contributing/changelogs/) is included
* [ ] At least one test case is included for this feature or bug fix
* [x] Documentation was added or is not needed

* [?] This is an API breaking change

### Issue Resolved / Feature Added
Characters are vertically clipped when the font doesn't specify proper metrics.

### Resolution
Unilaterally assign basic, low-level, easy to override, line-height measurements based on our existing definitions.

### CODE REVIEW

**Comment by Djspaceg** [comment]
VideoPlayer does actually have a non-Latin line height definition a few lines below, so it should not be a problem.
https://github.com/enactjs/enact/blob/c0f978cc66e442146670e33e0e254d2a5fd6d86b/packages/moonstone/VideoPlayer/VideoPlayer.less#L110

The other two _shouldn't_ be a problem, but still worth verifying that things aren't terribly broken.

**Comment by ryanjduffy** [comment]
That would be great. Should we remove those `line-height` rules in this PR since they have no effect and would only confuse future us?

**Comment by Djspaceg** [comment]
That is a negative, Red Leader. non-Latin header line-height is 1.5em while our standard non-Latin is 1.7em (to account for things like Thai tall characters). Header line-height we can more tightly assign than generalized body text because we're (the Framework is) responsible for the layout and possible region overlap of our Header component.

**Comment by ryanjduffy** [comment]
:+1: I was only thinking of non-latin but the `line-height` rules would still take effect in latin locales.

**Pull request merged**
