### PR TITLE
ENYO-5979: Fix VL unexpected focus change to to last focused items

### PR DESCRIPTION
**Pull request by germboy**
### Checklist

* [x] I have read and understand the [contribution guide](http://enactjs.com/docs/developer-guide/contributing/)
* [ ] A [CHANGELOG entry](http://enactjs.com/docs/developer-guide/contributing/changelogs/) is included
* [ ] At least one test case is included for this feature or bug fix
* [x] Documentation was added or is not needed

* [ ] This is an API breaking change

### Issue Resolved / Feature Added
There are cases where `VirtualList` focus could unexpectedly change to a last-focused item.

### Resolution
Each time when setting focus to "next" items, `VirtualList` was needlessly setting the current index value to `this.nodeIndexToBeFocused`. This value only needs to be set prior to explicitly setting scroll position/focus elsewhere (e.g. a wrap or page event). As a result, `this.nodeIndexToBeFocused` was not being nullified, causing unexpected focus changes when items were mounted.

### CODE REVIEW

**Comment by ryanjduffy** [comment]
@germboy Is this a regression from the changes in `develop`? If so, should it be fixed there?

**Comment by germboy** [comment]
@ryanjduffy Perhaps you're right. I think the side-effect of the issue is only seen in `feature/ui-update`, but yeah - the source of the problem still exists in `develop`.

**Comment by germboy** [comment]
@ryanjduffy I opened #2336 against `develop`. That PR also correctly sets the `this.lastFocusedIndex` value, since it was not updated in `develop`

**Comment by ryanjduffy** [comment]
Closing this in favor of #2336 which has been merged into `feature/ui-update` as well.

**Pull request closed without merging**
