### PR TITLE
ENYO-6151: Fix focused, high contrast, and disabled appearance of expandables

### PR DESCRIPTION
**Pull request by teckliew**
### Checklist

* [x] I have read and understand the [contribution guide](http://enactjs.com/docs/developer-guide/contributing/)
* [x] A [CHANGELOG entry](http://enactjs.com/docs/developer-guide/contributing/changelogs/) is included
* [ ] At least one test case is included for this feature or bug fix
* [x] Documentation was added or is not needed

* [ ] This is an API breaking change

### Issue Resolved / Feature Added
[//]: # (Describe the issue resolved or feature added by this pull request)
Fix `moonstone/DatePicker`, `moonstone/DayPicker`, `moonstone/ExpandableList`, and `moonstone/TimePicker` disabled opacity to be consistent across high contrast skins.

Root cause:
When there are two layers in a component that receive `disabled` prop, both of these layers will also receive disabled rules from `.moonstone`/`.moonstone-light`; as a result it can be visibly seen that opacity disabled rule is applied twice.
To counter this, one layer has to explicitly unset the default disabled rules as seen on L49. This allows `ExpandableItem` to have full opacity while its child `LabeledItem` will be visibly disabled as normal.
The issue is reintroduced when `.highContrast` or when any skin is applied, and the default disabled opacity rule has a higher specificity as a result, overriding L49.
Wrapping `.disabled` rule with `Skinnable` will apply the opacity override across different skins.

### Links
[//]: # (Related issues, references)
ENYO-6151

### CODE REVIEW

**Comment by ryanjduffy** [comment]
@teckliew Can you add some explanation to the description on the root cause of the problem and why the proposed fix resolves it? :awthanks:

**Comment by teckliew** [comment]
:yougotitdude:

**Comment by ryanjduffy** [comment]
@teckliew Thanks for the analysis on this. I think you're on the right track with a specificity fix. I searched through the code base for other instances of `.disabled()` with opacity and found that the other cases were wrapped with `.applySkins()` as well which fixes the specificity issue.

What do you think of changing ExpandableItem to wrap `.disabled()` with `.applySkins()` as well?

**Comment by teckliew** [comment]
Yep that sounds good 👍

**Pull request merged**
