### PR TITLE
ENYO-5348: Add issue templates

### PR DESCRIPTION
**Pull request by webOS101**
Enact-DCO-1.0-Signed-off-by: Roy Sutton roy.sutton@lge.com

### Issue Resolved / Feature Added
[//]: # (Describe the issue resolved or feature added by this pull request)
Adds issue templates

### Resolution
[//]: # (Does the code work as intended?)
[//]: # (What is the impact of this change and *why* was it made?)
Don't know if it works!  No way to preview, AFAIK.

### Additional Considerations
[//]: # (How should the change be tested?)
[//]: # (Are there any outstanding questions?)
[//]: # (Were any side-effects caused by the change?)
Perhaps I should rebase this back to `master` so we can try it out now?

### Links
[//]: # (Related issues, references)

### CODE REVIEW

**Comment by webOS101** [comment]
If they were just in parens, then they would litter our PR's and Issues with noise.  We've been using them in our PR template for a year now and I haven't heard any complaints.

**Comment by Djspaceg** [comment]
It's just an extra step I have to do to delete them out of every PR I make. If someone misunderstands the intent of them, then their text is either omitted (due to being commented out) or they retain a bunch of non-human-readable characters in their comment.

**Comment by webOS101** [comment]
You don't have to delete them.  They're just comments, they disappear when not submitting the PR.

**Comment by Djspaceg** [comment]
The headings remain even if there are no contents to that section. Your PR is then littered with a bunch of irrelevant unused headings, drawing attention away from the meaningful parts.

**Comment by webOS101** [comment]
That's a different issue that the one you raised about the [//] lines.  If the headings aren't useful, then we could remove those sections.

**Comment by ryanjduffy** [comment]
Went ahead and merged this despite the ongoing conversation. Happy to take additional changes to improve these templates.

**Pull request merged**
