### PR TITLE
ENYO-6286: Update Marquee to new repeated content style

### PR DESCRIPTION
**Pull request by ryanjduffy**
### Checklist

* [X] I have read and understand the [contribution guide](http://enactjs.com/docs/developer-guide/contributing/)
* [X] A [CHANGELOG entry](http://enactjs.com/docs/developer-guide/contributing/changelogs/) is included
* [ ] At least one test case is included for this feature or bug fix
* [X] Documentation was added or is not needed

* [ ] This is an API breaking change

### Issue Resolved / Feature Added
[//]: # (Describe the issue resolved or feature added by this pull request)
* Marquee style has changed from single copy of text to duplicated text with configurable padding.
* Text continues to be truncated with an ellipsis when it exceeds the width of its container.

### Resolution
[//]: # (Does the code work as intended?)
[//]: # (What is the impact of this change and *why* was it made?)
* Add `marqueeSpacing` to configure padding either relative to the container (e.g. `'50%'`) or absolutely (e.g. `200`) which is scaled for the current resolution
* Add `spacing` class to CSS overrides to customize the styling of the padding node
* Update `MarqueeDecorator` to calculate the new distance and spacing
* Update `MarqueeBase` to duplicate the content just before animating when distance requires it.

### CODE REVIEW

**Comment by Djspaceg** [comment]
Can we change "padding" to "spacing" to avoid using the name of a CSS property?

**Comment by germboy** [comment]
This looks good to me. I didn't notice any real behavior or performance changes that would concern me too much. When the marquee completes (and the overflowing text changes to ellipsis), it appears that the text itself shifts to the right by a few pixels. I don't know if this is something hat can be prevented or would concern anyone. Could you confirm this behavior? Otherwise, I'm good to approve this PR.

**Comment by ryanjduffy** [comment]
I think there are two issues at play here.

* There's a rounding error when using `scrollWidth` because it only reports whole pixel values. There isn't a whole lot we can do about this as far as I can tell but generally isn't very disruptive.
* `moonstone/Panels.Header` includes a `text-indent` on the `.title` which messes with the alignment of the duplicated content since it isn't indented.

I've pushed a fix for the latter which required touching other bits of Marquee and Header to get everything landing where it should.

cc: @Djspaceg

**Comment by ryanjduffy** [comment]
Realized after I walked away that I don't want to forward `css` through MarqueeDecorator but the effect will be the same for the purposes of the result in Header.

**Comment by ryanjduffy** [comment]
Pushed a fix for the improper Marquee css override approach

**Comment by Djspaceg** [comment]
Should the `.spacing` class be renamed since it's a really common term and is now being exported for override? `.marqueeSpacing` at the simplest.

**Comment by ryanjduffy** [comment]
@Djspaceg I think the concern over naming is valid -- we've had cases where we've inadvertently overridden classes. Do you think this class is more common than others and therefore should be changed?

**Comment by Djspaceg** [comment]
> @Djspaceg I think the concern over naming is valid -- we've had cases where we've inadvertently overridden classes. Do you think this class is more common than others and therefore should be changed?

Well, `.text`, `.animate`, and `.willAnimate` seem likely to also exist organically, but those are pre-existing names, so we can't do much about those; but we _could_ do something about the new `.spacing`. **Alternatively** having to be concerned about what external things are doing is pretty lame and makes modular CSS less awesomely isolated; so maybe NBD. I'm sort of torn now.

**Pull request merged**
