### PR TITLE
PLAT-78725:  Fix VirtualGridList to work properly with `wrap` prop

### PR DESCRIPTION
**Pull request by 0x64**
### Checklist

* [x] I have read and understand the [contribution guide](http://enactjs.com/docs/developer-guide/contributing/)
* [ ] A [CHANGELOG entry](http://enactjs.com/docs/developer-guide/contributing/changelogs/) is included
* [ ] At least one test case is included for this feature or bug fix
* [x] Documentation was added or is not needed
* [ ] This is an API breaking change

### Issue Resolved / Feature Added
[//]: # (Describe the issue resolved or feature added by this pull request)
`wrap` feature is broken after #2239. (A kind of regression)

### Resolution
[//]: # (Does the code work as intended?)
[//]: # (What is the impact of this change and *why* was it made?)
Added missing condition.

### Additional Considerations
[//]: # (How should the change be tested?)
[//]: # (Are there any outstanding questions?)
[//]: # (Were any side-effects caused by the change?)
Fixed the regression before any release, so there is no change log.

### Links
[//]: # (Related issues, references)
PLAT-78725

### CODE REVIEW

**Comment by seunghoh** [comment]
LGTM

**Comment by ryanjduffy** [comment]
I'm expecting this is broken in `develop`. If so, this should either be retargeted to `develop` or cherry picked back there after merging.

**Comment by webOS101** [comment]
I believe this regression was introduced when we removed the disabled skipping code.  But, I can't test VGL on `develop` right now.

**Comment by ryanjduffy** [comment]
Based on @webOS101 and @0x64 comments that this was regression from #2239, this is the right branch for the fix. :nothingtodohere:

**Comment by webOS101** [comment]
Confirmed issue does not reproduce on `develop`.

**Pull request merged**
