### PR TITLE
ENYO-5664: Add onHoldEnd event to Touchable

### PR DESCRIPTION
**Pull request by ryanjduffy**
### Checklist

* [x] I have read and understand the [contribution guide](http://enactjs.com/docs/developer-guide/contributing/)
* [x] A [CHANGELOG entry](http://enactjs.com/docs/developer-guide/contributing/changelogs/) is included
* [ ] At least one test case is included for this feature or bug fix
* [x] Documentation was added or is not needed

* [ ] This is an API breaking change

### Issue Resolved / Feature Added
[//]: # (Describe the issue resolved or feature added by this pull request)
No way to know when a hold ends to support longpress + drag interactions

### Resolution
[//]: # (Does the code work as intended?)
[//]: # (What is the impact of this change and *why* was it made?)
* Add `onHoldEnd` event to `ui/Touchable`
* Add `holdConfig.global` prop to opt-in to maintain hold when leaving node
* Update Hold and Drag to use `global` to indicate that a blur should not end the gesture

### CODE REVIEW

**Comment by webOS101** [comment]
Regarding 2, if we wanted to do that, we'd need to support both for now and deprecate the original event.

**Comment by ryanjduffy** [comment]
@germboy I see your point about the incongruence of `onHold` and `onHoldEnd`. Maybe `onReleaseHold` or `onHoldRelease` would soften that a bit? I don't think `onHoldStart` would convey the same message as `onHold`.

**Comment by webOS101** [comment]
`onUnhold`  :Shipit:

**Comment by webOS101** [comment]
More serious, `Start/End` mirror the touch events so it would be a useful analogy.

**Comment by ryanjduffy** [comment]
It's not a direct parallel though as it stands. I think we may have to rework the hold events to get the semantics the same:

 Now | Then
------|-----
| `onHold` | `onHoldStart` |
| `onHoldPulse` | `onHold` |
| --- | `onHoldEnd` |

**Comment by germboy** [comment]
@ryanjduffy  I think that makes sense, seeing it broken down like that. Ultimately we'd need `onHoldPulse` to become `onHold`, which we can't really do. :shipit:  for now and we can plan on changing the naming convention in the next major release. Approving 1st review, despite the changelog conflict.

**Pull request merged**
