### PR TITLE
WRQ-15921: Fix spotlight.disableSelector to set selectorDisabled to false

### PR DESCRIPTION
**Pull request by juwonjeong**
Enact-DCO-1.0-Signed-off-by: Juwon Jeong (juwon.jeong@lge.com)

### Checklist

* [x] I have read and understand the [contribution guide](http://enactjs.com/docs/developer-guide/contributing/)
* [x] A [CHANGELOG entry](http://enactjs.com/docs/developer-guide/contributing/changelogs/) is included
* [ ] At least one test case is included for this feature or bug fix
* [x] Documentation was added or is not needed
* [ ] This is an API breaking change

### Issue Resolved / Feature Added
[//]: # (Describe the issue resolved or feature added by this pull request)

### Resolution
[//]: # (Does the code work as intended?)
[//]: # (What is the impact of this change and *why* was it made?)
`enableSelector` needs to set selectorDisabled to true and `disableSelector` needs to set selectorDisabled to false.

### Additional Considerations
[//]: # (How should the change be tested?)
[//]: # (Are there any outstanding questions?)
[//]: # (Were any side-effects caused by the change?)

### Links
[//]: # (Related issues, references)
WRQ-15921

### CODE REVIEW

**Comment by 0x64** [comment]
Note: this PR fixes a bug from #703

**Comment by 0x64** [comment]
💯

**Comment by MikyungKim** [comment]
Shouldn't we add a change log for this?

**Review by MikyungKim — APPROVED** [review]
LGTM

**Pull request merged**
