### PR TITLE
PLAT-83166: Organized the Button CSS rules

### PR DESCRIPTION
**Pull request by Djspaceg**
### Checklist

* [x] I have read and understand the [contribution guide](http://enactjs.com/docs/developer-guide/contributing/)
* [ ] A [CHANGELOG entry](http://enactjs.com/docs/developer-guide/contributing/changelogs/) is included
* [ ] At least one test case is included for this feature or bug fix
* [x] Documentation was added or is not needed
* [ ] This is an API breaking change

### Issue Resolved / Feature Added
Many of `Button`s LESS variables are old and don't follow good naming conventions or linking practices.

### Resolution
`Button` LESS variables have been restructured and alphabetized in the `variables.less` file while the rules of `.moon-large-button-text()` and `.moon-small-button-text()` mixins, in the `mixins.less` file, have been pointed to their better-named equivalents.

This change intends zero visual (perceptible) difference from `develop`.

### CODE REVIEW

**Comment by webOS101** [comment]
Did any less variables get added/removed? If so, can you update the migration guide, too?

**Comment by Djspaceg** [comment]
Sure.

**Comment by webOS101** [comment]
I think for added (if they didn't have an equivalent before) then we don't have to document them in the migration guide.

**Comment by Djspaceg** [comment]
Updated the guide.

**Pull request merged**
