### PR TITLE
PLAT-77708: Reassigned several newly supported languages

### PR DESCRIPTION
**Pull request by Djspaceg**
### Checklist

* [x] I have read and understand the [contribution guide](http://enactjs.com/docs/developer-guide/contributing/)
* [x] A [CHANGELOG entry](http://enactjs.com/docs/developer-guide/contributing/changelogs/) is included
* [x] At least one test case is included for this feature or bug fix
* [x] Documentation was added or is not needed
* [ ] This is an API breaking change

### Issue Resolved / Feature Added
The system font now supports more language scripts

### Resolution
Updated several languages to get "non-latin" overrides so they get the correct font assignments.
Also added a basic font/language checking sample in QA Sampler.

### CODE REVIEW

**Comment by Djspaceg** [comment]
@webOS101, you'll need to clarify what your difficulties are. The fallbacks are indeed applied in the fonts definition file, and locale-specific fonts are applied in fontGenerator. What are you seeing? Do you see a better way to "couple" things?

**Comment by webOS101** [comment]
Aren't certain font or CSS properties applied depending on whether it's a latin or non-latin locale?

**Comment by Djspaceg** [comment]
That is correct.

**Comment by webOS101** [comment]
So, when the new fonts are not used, the following locales:  'el', 'bg', 'mk', 'mn', 'ru', 'uk', 'kk' will now render differently, will they not?

**Comment by Djspaceg** [comment]
They will indeed be rendered differently.

Followup question: What scenario are you referring to where the new fonts will not be used?

**Comment by webOS101** [comment]
I was thinking of cases of using Moonstone in the browser.

**Comment by Djspaceg** [comment]
You're describing a scenario which: runs a moonstone app in a generic Chrome browser, without LG TV fonts, but with a locale specified as one of the above, and are concerned that Miso or Museo Sans (the old fonts) don't have the correct glyphs available. The OS will provide the specific missing glyph in this case.

**Comment by webOS101** [comment]
:nothingtodohere:  :shipit:

**Pull request merged**
