### PR TITLE
WRP-4450: Update `@enact/docs-utils` version to 0.4.0

### PR DESCRIPTION
**Pull request by hong6316**
### Checklist

* [x] I have read and understand the [contribution guide](http://enactjs.com/docs/developer-guide/contributing/)
* [ ] A [CHANGELOG entry](http://enactjs.com/docs/developer-guide/contributing/changelogs/) is included
* [ ] At least one test case is included for this feature or bug fix
* [x] Documentation was added or is not needed
* [ ] This is an API breaking change

### Issue Resolved / Feature Added
[//]: # (Describe the issue resolved or feature added by this pull request)
As a result of the verification, it was confirmed that docs-utils 0.4.0 was available to include.
Update docs-utils version to 0.4.0 in enact dependency and remove workaround code from travis.yml.

### Resolution
[//]: # (Does the code work as intended?)
[//]: # (What is the impact of this change and *why* was it made?)
Fix docs-utils version to 0.4.0

### Additional Considerations
[//]: # (How should the change be tested?)
[//]: # (Are there any outstanding questions?)
[//]: # (Were any side-effects caused by the change?)
- Remove workaround code from travis.yml.

### Links
[//]: # (Related issues, references)

### Comments
Enact-DCO-1.0-Signed-off-by: Taeyoung Hong (taeyoung.hong@lge.com)

### CODE REVIEW

**Comment by hong6316** [comment]
I will revert the "fix lint errors" commit, this will be added in WRP-6651 PR.

**Comment by hong6316** [comment]
Using the current node(node19) will be fixed by sjro

**Comment by MikyungKim** [comment]
Please update your branch with the recent develop.

**Review by MikyungKim — APPROVED** [review]
LGTM

**Pull request merged**
