### PR TITLE
PLAT-81342: Assigned proper colors to RadioItem dot

### PR DESCRIPTION
**Pull request by Djspaceg**
### Checklist

* [x] I have read and understand the [contribution guide](http://enactjs.com/docs/developer-guide/contributing/)
* [x] A [CHANGELOG entry](http://enactjs.com/docs/developer-guide/contributing/changelogs/) is included
* [ ] At least one test case is included for this feature or bug fix
* [x] Documentation was added or is not needed
* [ ] This is an API breaking change

### Issue Resolved / Feature Added
Who initially came up with these RadioItem dot colors?? J/k, it was likely me. New design colors have been delivered and need to be implemented.

### Resolution
Implemented new colors to match designs, which also bring dark and light skins inline with each other.

### CODE REVIEW

**Comment by ryanjduffy** [comment]
@Djspaceg + @teckliew - Can we revise the high contrast bg color in the dark skin? It does not have enough contrast, imo.

image

**Comment by Djspaceg** [comment]
Of course! I believe that light gray is actually supposed to be black in high-contrast. I'll make the change now.

**Comment by Djspaceg** [comment]
My mistake. They are the way they're intended to be:
From the design document:
Screen Shot 2019-07-22 at 12 02 50 PM

**Comment by ryanjduffy** [comment]
Okay!

**Pull request merged**
