### PR TITLE
PLAT-75393 - Added stopPropagation to ToggleIcon

### PR DESCRIPTION
**Pull request by rundmt**
### Checklist

* [x] I have read and understand the [contribution guide](http://enactjs.com/docs/developer-guide/contributing/)
* [x] A [CHANGELOG entry](http://enactjs.com/docs/developer-guide/contributing/changelogs/) is included
* [x] At least one test case is included for this feature or bug fix
* [ ] Documentation was added or is not needed

* [ ] This is an API breaking change

### Issue Resolved / Feature Added
RadioItem was firing twice when being tapped on.

### Resolution
Add stopPropagation to `ToggleIcon` to stop it from firing twice.

### Additional Considerations
Seems to work so far. I'm making this a draft for now while I write tests. I'm having some trouble reproducing the bug in unit tests.

### Links
PLAT-75393

### CODE REVIEW

**Comment by rundmt** [comment]
@ryanjduffy Yeah that is strange I'll take it look at it.

**Comment by ryanjduffy** [comment]
@rundmt - I don't think the updated approach is going to work. I wasn't able to test it on my Surface table (it's reporting `false` for touch for some reason ...) but when i force `touch` to true to simulate a dual touch/pointer scenario, Slider doesn't drag.

It does seem to work on the reported problem so that might give us a hint that the issue lies in the handling of both mouse and touch events.

**Comment by webOS101** [comment]
@ryanjduffy Can you share what your user agent is for the surface?  Curious why we're not detecting it properly.  I suspect it might be because Edge now supports this:  https://developer.mozilla.org/en-US/docs/Web/API/Navigator/maxTouchPoints instead of the prefixed version.  Looks like we need to update our logic in `hasTouch()`

**Comment by ryanjduffy** [comment]
I tried edge but it was so wonky on first render i didn't even try it really. I was testing in Chrome which wasn't reporting `ontouchstart` in window.

**Comment by webOS101** [comment]
Does it have `maxTouchPoints`?

**Comment by ryanjduffy** [comment]
@rundmt I think I've tracked down the issue. Here's my alternative:

https://github.com/enactjs/enact/pull/2192

**Comment by rundmt** [comment]
@ryanjduffy Ahh I see, this does look better. I totally forgot we had the timestamp problems with mouse. It does seem to work, I'll approve the other PR and use that one to replace this one.

**Comment by rundmt** [comment]
Closing in favor of #2192

**Pull request closed without merging**
