### PR TITLE
ENYO-5338: Add positionContextualPopup method

### PR DESCRIPTION
**Pull request by viodragon2**
### Issue Resolved / Feature Added
[//]: # (Describe the issue resolved or feature added by this pull request)
`moonstone/ContextualPopup` may need to update its position if the position or dimensions of the activator or popup updates. Unfortunately, `moonstone/ContextualPopupDecorator` is not suited for monitoring those states. We can think about different ways of handling positioing so that it always positions relative to the activator and the window. Howver, given the complexity and time required for the suggested change, we choose to provide an imperative API for developers to call `positionContextualPopup` method to adjust positions if needed.

See also: #1717 

Enact-DCO-1.0-Signed-off-by: Stephen Choi <stephen.choi@lge.com>

### CODE REVIEW

**Comment by ryanjduffy** [comment]
WDYT of ```
	const Decorator = hoc(...);
	return compose(
		ApiDecorator,
		Subscription({
			channels: ['i18n'],
			mapMessageToProps: (key, {rtl}) => ({rtl})
		}),
		Decorator
	);
```

**Comment by viodragon2** [comment]
I've thought about that. The only (minor) problem I had with that was the it needed to have a separate name other than `ContextualPopupDecorator`. IOW,
```
	const Decorator = hoc(...);
	const ContextualPopupDecorator = compose(
		ApiDecorator,
		Subscription({
			channels: ['i18n'],
			mapMessageToProps: (key, {rtl}) => ({rtl})
		}),
		Decorator
	);

export default ContextualPopupDecorator;
export {ContextualPopupDecorator}

```

And where does the doc belong to in this case? `Decorator` or `ContextualPopupDecorator`?

**Comment by ryanjduffy** [comment]
I don't think it greatly matters on which you document it. My take would be to document on the member named after the export.

**Comment by viodragon2** [comment]
Updated per discussion!

**Pull request merged**
